name: ðŸ”§ Java CI with Maven

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout Code
        uses: actions/checkout@v3

      - name: â˜• Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: ðŸ“¦ Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: ðŸ›  Build with Maven
        run: mvn clean install -DskipTests=true

      - name: âœ… Run Tests with Maven
        run: mvn test

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARTOKEN  }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=master-devops-cloud2_yassine-ghalim \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=master-devops-cloud2 \
            -Dsonar.login=${{ secrets.SONARTOKEN  }}  

      - name: ðŸ“¤ Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports
